### ISSUE TITLE
Security Mechanism's Vulnerabilities

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/security-ontology#1]
According to ROSE, only `Object at Risk` and `Risk Enablers` have `Vulnerabilty`. However, `Security Mechanism` also have `Vulnerability`.

**Comment by italojsoliveira** [comment]
In principle, `Object at Risk`, `Security Mechanism`, and `Risk Enablers` are **not** disjoint types. So, a `Security Mechanism` can also be an `Object at Risk`.
